//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelperToolRenovado {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelperToolRenovado.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate Windows.
        /// </summary>
        internal static string btnActivateWindows {
            get {
                return ResourceManager.GetString("btnActivateWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activation Settings.
        /// </summary>
        internal static string btnActivationSettings {
            get {
                return ResourceManager.GetString("btnActivationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced Menu.
        /// </summary>
        internal static string btnAdvancedMenuW {
            get {
                return ResourceManager.GetString("btnAdvancedMenuW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deactivate Windows.
        /// </summary>
        internal static string btnDeactivateWindows {
            get {
                return ResourceManager.GetString("btnDeactivateWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimize Now.
        /// </summary>
        internal static string btnGoAdvancedOptions {
            get {
                return ResourceManager.GetString("btnGoAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimize Menu.
        /// </summary>
        internal static string btnOptimizeMenu {
            get {
                return ResourceManager.GetString("btnOptimizeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimize Settings.
        /// </summary>
        internal static string btnOptimizeSettings {
            get {
                return ResourceManager.GetString("btnOptimizeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimize Now.
        /// </summary>
        internal static string btnOptmizeNow {
            get {
                return ResourceManager.GetString("btnOptmizeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roll Back.
        /// </summary>
        internal static string btnRollback2 {
            get {
                return ResourceManager.GetString("btnRollback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Windows Version.
        /// </summary>
        internal static string btnShowWversion {
            get {
                return ResourceManager.GetString("btnShowWversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Delete fast acces folder.
        /// </summary>
        internal static string checkBoxDelFastAccs {
            get {
                return ResourceManager.GetString("checkBoxDelFastAccs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Delete image folder.
        /// </summary>
        internal static string checkBoxDelImage {
            get {
                return ResourceManager.GetString("checkBoxDelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Delete music folder.
        /// </summary>
        internal static string checkBoxDelMusic {
            get {
                return ResourceManager.GetString("checkBoxDelMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Delete objects3D folder.
        /// </summary>
        internal static string checkBoxDelObjects {
            get {
                return ResourceManager.GetString("checkBoxDelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Delete video folder.
        /// </summary>
        internal static string checkBoxDelVideo {
            get {
                return ResourceManager.GetString("checkBoxDelVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable Windows Defender.
        /// </summary>
        internal static string checkBoxDisableDefender {
            get {
                return ResourceManager.GetString("checkBoxDisableDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable Firewall.
        /// </summary>
        internal static string checkBoxDisableFirewall {
            get {
                return ResourceManager.GetString("checkBoxDisableFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable all Windows notifications.
        /// </summary>
        internal static string checkBoxDisableNotifications {
            get {
                return ResourceManager.GetString("checkBoxDisableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable run as administrator messages.
        /// </summary>
        internal static string checkBoxDisableRunasAdmin {
            get {
                return ResourceManager.GetString("checkBoxDisableRunasAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Unistall OneDrive.
        /// </summary>
        internal static string checkBoxUnistallOneDrive {
            get {
                return ResourceManager.GetString("checkBoxUnistallOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Clear DNS cache.
        /// </summary>
        internal static string checkCacheDNS {
            get {
                return ResourceManager.GetString("checkCacheDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Clear cache.
        /// </summary>
        internal static string checkClearCache {
            get {
                return ResourceManager.GetString("checkClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Clear event log.
        /// </summary>
        internal static string checkClearEvLog {
            get {
                return ResourceManager.GetString("checkClearEvLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Clear Recycle bin.
        /// </summary>
        internal static string checkClearRecyclebin {
            get {
                return ResourceManager.GetString("checkClearRecyclebin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Delete temporary files.
        /// </summary>
        internal static string checkDeleteTempFiles {
            get {
                return ResourceManager.GetString("checkDeleteTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Delete temporary files from windows updates.
        /// </summary>
        internal static string checkDelTempFilesUpdate {
            get {
                return ResourceManager.GetString("checkDelTempFilesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable game Mode.
        /// </summary>
        internal static string checkDisableGameModeWin {
            get {
                return ResourceManager.GetString("checkDisableGameModeWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable windows Push notification service.
        /// </summary>
        internal static string checkDisablePushN {
            get {
                return ResourceManager.GetString("checkDisablePushN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable windows search.
        /// </summary>
        internal static string checkDisableSearch {
            get {
                return ResourceManager.GetString("checkDisableSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable unnecessary services.
        /// </summary>
        internal static string checkDisableServices {
            get {
                return ResourceManager.GetString("checkDisableServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable Sysmain.
        /// </summary>
        internal static string checkDisableSysM {
            get {
                return ResourceManager.GetString("checkDisableSysM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Disable windows update.
        /// </summary>
        internal static string checkDisableUpdates {
            get {
                return ResourceManager.GetString("checkDisableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Maximum performance energy plan.
        /// </summary>
        internal static string checkEnergyPlan {
            get {
                return ResourceManager.GetString("checkEnergyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimize Options.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced Options.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check All.
        /// </summary>
        internal static string lblCheckAll {
            get {
                return ResourceManager.GetString("lblCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check All.
        /// </summary>
        internal static string lblCheckAll2 {
            get {
                return ResourceManager.GetString("lblCheckAll2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait this will take a few minutes ....
        /// </summary>
        internal static string lblPleaseWait {
            get {
                return ResourceManager.GetString("lblPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UnCheck All.
        /// </summary>
        internal static string lblUncheckAll {
            get {
                return ResourceManager.GetString("lblUncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UnCheck All.
        /// </summary>
        internal static string lblUncheckAll2 {
            get {
                return ResourceManager.GetString("lblUncheckAll2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to HelperTool
        ///
        ///
        ///
        ///         ENJOY IT &lt;3.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to activate.
        /// </summary>
        internal static string mensajeActivacion {
            get {
                return ResourceManager.GetString("mensajeActivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your operating system : {{windowsVersion}} has been successfully activated.
        /// </summary>
        internal static string mensajeActivacionCorrecta {
            get {
                return ResourceManager.GetString("mensajeActivacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To see the applied changes you need to restart the system. Do you want to do it now?.
        /// </summary>
        internal static string mensajeCambiosAplicadosReiniciar {
            get {
                return ResourceManager.GetString("mensajeCambiosAplicadosReiniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember that this function is only a demonstration of how it will work, it does not actually activate your operating system. If you want to activate your operating system, buy an official Windows license..
        /// </summary>
        internal static string mensajeDemostracion {
            get {
                return ResourceManager.GetString("mensajeDemostracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to deactivate windows?.
        /// </summary>
        internal static string mensajeDesactivacion {
            get {
                return ResourceManager.GetString("mensajeDesactivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to optimize now?.
        /// </summary>
        internal static string mensajeDeseaOptimizar {
            get {
                return ResourceManager.GetString("mensajeDeseaOptimizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to restart to apply the changes?.
        /// </summary>
        internal static string mensajeDeseaReiniciar {
            get {
                return ResourceManager.GetString("mensajeDeseaReiniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your windows version has not been found!!!!!
        ///Remember that this program only supports licenses of :
        ///Windows 10 Pro &amp; Windows 11 Pro.
        ///Windows 10 Home &amp; Windows 11 Home.
        ///Windows 10 Enterprise &amp; Windows 11 Enterprise.
        ///Windows 10 Education &amp; Windows 11 Education..
        /// </summary>
        internal static string mensajeErrorVersion {
            get {
                return ResourceManager.GetString("mensajeErrorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows has ben optimized sucefull!!.
        /// </summary>
        internal static string mensajeOptimizadoCorrectamente {
            get {
                return ResourceManager.GetString("mensajeOptimizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to rollback? If you do, the optimization options will be as before.
        /// </summary>
        internal static string mensajeRollBackPregunta {
            get {
                return ResourceManager.GetString("mensajeRollBackPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The rollback was successful!.
        /// </summary>
        internal static string mensajeRollbackSuccefull {
            get {
                return ResourceManager.GetString("mensajeRollbackSuccefull", resourceCulture);
            }
        }
    }
}
