//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelperToolRenovado {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelperToolRenovado.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar Windows.
        /// </summary>
        internal static string btnActivateWindows {
            get {
                return ResourceManager.GetString("btnActivateWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Herramientas de Activacion.
        /// </summary>
        internal static string btnActivationSettings {
            get {
                return ResourceManager.GetString("btnActivationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu de Opciones Avanzadas.
        /// </summary>
        internal static string btnAdvancedMenuW {
            get {
                return ResourceManager.GetString("btnAdvancedMenuW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desactivar Windows.
        /// </summary>
        internal static string btnDeactivateWindows {
            get {
                return ResourceManager.GetString("btnDeactivateWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimizar Ahora.
        /// </summary>
        internal static string btnGoAdvancedOptions {
            get {
                return ResourceManager.GetString("btnGoAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu de Optimizacion.
        /// </summary>
        internal static string btnOptimizeMenu {
            get {
                return ResourceManager.GetString("btnOptimizeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Herramientas de Optimizacion.
        /// </summary>
        internal static string btnOptimizeSettings {
            get {
                return ResourceManager.GetString("btnOptimizeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimizar Ahora.
        /// </summary>
        internal static string btnOptmizeNow {
            get {
                return ResourceManager.GetString("btnOptmizeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshcer todo.
        /// </summary>
        internal static string btnRollback2 {
            get {
                return ResourceManager.GetString("btnRollback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar mi version de Windows.
        /// </summary>
        internal static string btnShowWversion {
            get {
                return ResourceManager.GetString("btnShowWversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Eliminar acceso rapido .
        /// </summary>
        internal static string checkBoxDelFastAccs {
            get {
                return ResourceManager.GetString("checkBoxDelFastAccs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Eliminar carpeta Imagenes.
        /// </summary>
        internal static string checkBoxDelImage {
            get {
                return ResourceManager.GetString("checkBoxDelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Eliminar carpeta Musica.
        /// </summary>
        internal static string checkBoxDelMusic {
            get {
                return ResourceManager.GetString("checkBoxDelMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Eliminar carpeta Objetos3D.
        /// </summary>
        internal static string checkBoxDelObjects {
            get {
                return ResourceManager.GetString("checkBoxDelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Eliminar carpeta Videos.
        /// </summary>
        internal static string checkBoxDelVideo {
            get {
                return ResourceManager.GetString("checkBoxDelVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Desactivar Windows Defeneder.
        /// </summary>
        internal static string checkBoxDisableDefender {
            get {
                return ResourceManager.GetString("checkBoxDisableDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Desactivar Firewall.
        /// </summary>
        internal static string checkBoxDisableFirewall {
            get {
                return ResourceManager.GetString("checkBoxDisableFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Desactivar notificaciones de windows.
        /// </summary>
        internal static string checkBoxDisableNotifications {
            get {
                return ResourceManager.GetString("checkBoxDisableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Desactivar notificaciones de ejecutar como administrador.
        /// </summary>
        internal static string checkBoxDisableRunasAdmin {
            get {
                return ResourceManager.GetString("checkBoxDisableRunasAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Desinstalar OneDrive.
        /// </summary>
        internal static string checkBoxUnistallOneDrive {
            get {
                return ResourceManager.GetString("checkBoxUnistallOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Borrar caché DNS.
        /// </summary>
        internal static string checkCacheDNS {
            get {
                return ResourceManager.GetString("checkCacheDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Borrar caché.
        /// </summary>
        internal static string checkClearCache {
            get {
                return ResourceManager.GetString("checkClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Borrar registro de eventos.
        /// </summary>
        internal static string checkClearEvLog {
            get {
                return ResourceManager.GetString("checkClearEvLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Vaciar papelera de reciclaje.
        /// </summary>
        internal static string checkClearRecyclebin {
            get {
                return ResourceManager.GetString("checkClearRecyclebin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Borrar archivos temporales.
        /// </summary>
        internal static string checkDeleteTempFiles {
            get {
                return ResourceManager.GetString("checkDeleteTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Borrar archivos temporales de actualizaciones en windows.
        /// </summary>
        internal static string checkDelTempFilesUpdate {
            get {
                return ResourceManager.GetString("checkDelTempFilesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Deshabilitar modo juego de windows.
        /// </summary>
        internal static string checkDisableGameModeWin {
            get {
                return ResourceManager.GetString("checkDisableGameModeWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Deshabilitar notificaciones (Windows push).
        /// </summary>
        internal static string checkDisablePushN {
            get {
                return ResourceManager.GetString("checkDisablePushN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Deshabilitar Busqueda de Windows.
        /// </summary>
        internal static string checkDisableSearch {
            get {
                return ResourceManager.GetString("checkDisableSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Deshabilitar Servicios Innecesarios.
        /// </summary>
        internal static string checkDisableServices {
            get {
                return ResourceManager.GetString("checkDisableServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Deshabilitar SysMain (servicio).
        /// </summary>
        internal static string checkDisableSysM {
            get {
                return ResourceManager.GetString("checkDisableSysM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Deshabilitar Actualizaciones de Windows.
        /// </summary>
        internal static string checkDisableUpdates {
            get {
                return ResourceManager.GetString("checkDisableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Plan de energia Maximo Rendimiento.
        /// </summary>
        internal static string checkEnergyPlan {
            get {
                return ResourceManager.GetString("checkEnergyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones de Optimizacion.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones Avanzadas.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar todo.
        /// </summary>
        internal static string lblCheckAll {
            get {
                return ResourceManager.GetString("lblCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar todo.
        /// </summary>
        internal static string lblCheckAll2 {
            get {
                return ResourceManager.GetString("lblCheckAll2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esto tomara solo un par de segundos ....
        /// </summary>
        internal static string lblPleaseWait {
            get {
                return ResourceManager.GetString("lblPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desmarcar todo.
        /// </summary>
        internal static string lblUncheckAll {
            get {
                return ResourceManager.GetString("lblUncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desmarcar todo.
        /// </summary>
        internal static string lblUncheckAll2 {
            get {
                return ResourceManager.GetString("lblUncheckAll2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a HelperTool
        ///
        ///
        ///
        ///         Disfrutalo =D.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro de que desea activar windows?.
        /// </summary>
        internal static string mensajeActivacion {
            get {
                return ResourceManager.GetString("mensajeActivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su sistema operativo {{windowsVersion}} ha sido correctamente activado.
        /// </summary>
        internal static string mensajeActivacionCorrecta {
            get {
                return ResourceManager.GetString("mensajeActivacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerde que esta funcion es solo una demostracion de como funcionaria, esto no activa realmente tu sistema operativo. Si deseas activar tu Sistema operativo compra una licencia oficial de Windows..
        /// </summary>
        internal static string mensajeDemostracion {
            get {
                return ResourceManager.GetString("mensajeDemostracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro de que desea desactivar widows?.
        /// </summary>
        internal static string mensajeDesactivacion {
            get {
                return ResourceManager.GetString("mensajeDesactivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su version de windows no ha sido encontradada!!!!!
        ///Recuerde que este programa solo soporta licencias para:
        ///Windows 10 Pro &amp; Windows 11 Pro.
        ///Windows 10 Home &amp; Windows 11 Home.
        ///Windows 10 Enterprise &amp; Windows 11 Enterprise.
        ///Windows 10 Education &amp; Windows 11 Education..
        /// </summary>
        internal static string mensajeErrorVersion {
            get {
                return ResourceManager.GetString("mensajeErrorVersion", resourceCulture);
            }
        }
    }
}
